### ISSUE TITLE
Crash on a particular search

### ISSUE THREAD

**Issue by CottonEaster** [DoTheEvo/ANGRYsearch#40]
If I search for `google (` - not in regEx mode, and whether or not the check box is enabled - AngrySearch crashes to desktop, i.e. disappears. Perhaps the problem has to do with the database. However, updating the database did not solve the problem.

AngrySearch version: unknown, but I updated the program (as I've done before) via git cloning a few days ago.

Mint 18.2 x64 Cinnamon.

**Comment by DoTheEvo** [comment]
update to the latest from 4 days ago parentheses crash is fixed there

**Comment by CottonEaster** [comment]
I am afraid that I still get the crash even after updating. If you tell/remind me how to check the version number, I'll make sure I'm actually running the newest version (and haven't messed up the install somehow). Thanks.

**Comment by DoTheEvo** [comment]
tray icon, right click

**Comment by CottonEaster** [comment]
Sorry to be a pain, but my Cinnamon DE is showing no tray icon for AngrySearch (and I can't see an option in the config file for one). True, I see a tray icon for AngrySearch if I add the 'window list' applet to my panel, _but_ that icon has no options. Nor does my dock - which is Plank, and which I use instead of the aforementioned window list applet - help; it does show an AngrySearch icon, but, again, it shows no options.

**Comment by DoTheEvo** [comment]
open in any text editor `/usr/share/angrysearch/angrysearch.py`
search for `v1' should look [like this](http://i.imgur.com/74J8Jdj.png) but that version number was there for several commits

so if you have it open, check the [relevant part](http://i.imgur.com/EWnw8d1.png) for the parenthesis ignoring, at 1046 line, search for text `problematic`

if version is fine, and the 1046 line is there same and you still have issues, run angrysearch in terminal and screenshot the error you get when it crashes on input.

**Comment by CottonEaster** [comment]
Thanks. My version of the program does indeed have

```
# INSTEAD OF re.escape() PROBLEMATIC CHARACTERS ARE REMOVED
            for x in ['\"', '\'', '\\', '?', '+', '[', ']', '(', ')', '*']:
```

What I have found is curious! To wit: if AngrySearch is run from the terminal, then searching for `google (` causes no crash but does produce errors in the terminal; and,, if AngrySearch is _not_ run from the terminal, then the search _does_ cause it to crash (i.e. close). The terminal output (from when it is run from the terminal):

```
Traceback (most recent call last):
  File "/usr/bin/angrysearch", line 75, in run
    cur.execute(q)
sqlite3.OperationalError: malformed MATCH expression: [google* (* ]
Traceback (most recent call last):
  File "/usr/bin/angrysearch", line 75, in run
    cur.execute(q)
```
